### PR TITLE
✨clap cli support

### PR DESCRIPTION
**Pull request by 0xClandestine**

### CODE REVIEW

**Comment by degatchi** [comment]
Should add some readme  updates - i've never used clap.

**Comment by degatchi** [comment]
and possibly the option to use clap or default settings

**Comment by 0xClandestine** [comment]
> and possibly the option to use clap or default settings

I got you, will clean up the readme and make args optional otherwise will default to your original implementation.

**Comment by degatchi** [comment]
the tests have errors

**Comment by 0xClandestine** [comment]
will get around to it, was a bit busy yesterday

**Review by degatchi — APPROVED** [review]
thank you!

**Pull request merged**
